version: '3.8'

services:
  ollama:
    environment:
        - OLLAMA_FLASH_ATTENTION=1
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
