model_list:
  - model_name: openai-gpt-4o
    litellm_params:
      model: text-completion-openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY
      api_version: 2023-12-01-preview
      api_base: os.environ/AZURE_DEPLOYMENT_URL
