[tool.poetry]
name = "model-test"
version = "0.1.0"
description = ""
authors = ["Joel Akeret <joel.akeret@ti&m.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ollama = "^0.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
